---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-userdata-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-config-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn
