---
- name: emqx~> Ensure package facts gathered
  ansible.builtin.package_facts:

- name: emqx~> Ensure emqx_installed fact configured
  ansible.builtin.set_fact:
    emqx_installed: "{{ 'emqx' in ansible_facts.packages }}"

- name: emqx~> Ensure emqx installed
  block:
    - name: emqx~> Ensure install script downloaded
      ansible.builtin.get_url:
        url: https://assets.emqx.com/scripts/install-emqx-deb.sh
        dest: '/tmp/emqx.sh'
        mode: '0777'
    - name: emqx~> Ensure install script executed
      ansible.builtin.command:
        cmd: '/tmp/emqx.sh'
      failed_when: false
      changed_when: false
    - name: emqx~> Ensure emqx installed
      ansible.builtin.apt:
        name: emqx
        state: present
        update_cache: true
      when: not ansible_check_mode
  when: not emqx_installed

- name: emqx~> Ensure service started
  ansible.builtin.service:
    name: emqx
    state: started
  when: not ansible_check_mode

- name: emqx~> Ensure configured
  ansible.builtin.template:
    src: emqx.conf
    dest: /etc/emqx/emqx.conf
    mode: '0644'
    backup: true
  notify: restart emqx
