---
- name: Ensure base task executed
  ansible.builtin.include_tasks:
    file: base.yml
    apply:
      tags: base
  tags: base

- name: Ensure zfs task executed
  ansible.builtin.include_tasks:
    file: zfs.yml
    apply:
      tags: zfs
  tags: zfs

- name: Ensure nfs task executed
  ansible.builtin.include_tasks:
    file: nfs.yml
    apply:
      tags: nfs
  tags: nfs

- name: Ensure wakeonlan task executed
  ansible.builtin.include_tasks:
    file: wakeonlan.yml
    apply:
      tags: wakeonlan
  tags: wakeonlan
