---
- name: Ensure base task executed
  ansible.builtin.include_tasks:
    file: base.yml
    apply:
      tags: base
  tags: base

- name: Ensure service facts gathered
  ansible.builtin.service_facts:
  tags: always

- name: Ensure upgrade task executed
  ansible.builtin.include_tasks:
    file: upgrade.yml
    apply:
      tags: upgrade
  tags: upgrade

- name: Ensure zfs task executed
  ansible.builtin.include_tasks:
    file: zfs.yml
    apply:
      tags: zfs
  tags: zfs

- name: Ensure nfs task executed
  ansible.builtin.include_tasks:
    file: nfs.yml
    apply:
      tags: nfs
  tags: nfs

- name: Ensure wakeonlan task executed
  ansible.builtin.include_tasks:
    file: wakeonlan.yml
    apply:
      tags: wakeonlan
  tags: wakeonlan

- name: Ensure emqx cluster configured
  ansible.builtin.include_tasks:
    file: emqx.yml
    apply:
      tags: emqx
  tags: emqx
  when: "'emqx' in group_names"
