---
- name: Add ansible user to sudoers
  community.general.sudoers:
    name: "ansible-user-sudoers"
    user: "{{ ansible_user }}"
    nopassword: true
    commands: ALL

- name: Ensure logind configured
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^{{ item }}"
    line: "{{ item }}"
    backup: true
  loop:
    - HandleLidSwitch=ignore
    - HandleLidSwitchDocked=ignore
    - HandleLidSwitchExternalPower=ignore
    - HandleSuspendKey=ignore
  notify: restart logind

- name: Ensure nfs configured
  ansible.builtin.include_role:
    name: geerlingguy.nfs
  when: nfs_exports|length
