kind: ENC[AES256_GCM,data:t+0jU7Zo,iv:xxWMzPYGD2LY/onlieUkTjtDQ+YRtfgq8J1rNyNV8Xo=,tag:97NZpM4NMLXa2sD7s1B1aA==,type:str]
ansible_host: ENC[AES256_GCM,data:Vu8s4HHCOC/Crr8=,iv:o3ei2M9hFOWfWUtQfImEm/x5hpnAuDPEoVky0id0qY0=,tag:Ujeqb3PxiArqn20TrWwVCg==,type:str]
nfs_exports:
    - ENC[AES256_GCM,data:WkWuoBXCDldlVC1Du789qy3Mkoz0HHEQzykJWXozM9eX72REf2XncvoYix7U+M2VRoFvxRHMbUlcDrOzDPU=,iv:/SuSP+kYr8R/Lp4QtjlBK1KoXedho5U/kCFm/eyocF8=,tag:1t43ZC+u5X3IWxfCyOFIQg==,type:str]
zfs_pools:
    - name: ENC[AES256_GCM,data:1oByEA==,iv:BtHrpsPMAcJtZy9x3vAe1I/Wcw52F7QCchwyMGUPFQM=,tag:a+2jSphM9j/FjpfK05DuzA==,type:str]
      mountpoint: ENC[AES256_GCM,data:nDF8vuA=,iv:REVubpS/nOmjCsKPRpFrBH1Pn5+ZOTDDkswLodk6d5I=,tag:rHJ9W3wQE4mvU6LkCynU6A==,type:str]
      devices:
        - ENC[AES256_GCM,data:+tKkYMD8/j0/ce3Fe6IGZEPZVoH3mOse6aEVQ23nLTVUFzXrztZPSmLBOQ==,iv:m8E3t9SvICAL7ilBdigs/f8CRnhCqpE4jYXDY9xGGj0=,tag:rB16ABT9QXE9MwvY9tR3nA==,type:str]
      state: ENC[AES256_GCM,data:wpeuTySrgA==,iv:Dy79Xj0LBTDwr+ZNo1KOgsRZ4RqCTp+cs4jm4gLTZYA=,tag:sD7BMIv8t4doK2h8E7wG4Q==,type:str]
zfs:
    - ENC[AES256_GCM,data:3MRMVSPc0Eg=,iv:g6fmlXcPHIOZ1OO9LwvA/CEfL44fHu4tYGn3Wt5g/M4=,tag:Bs1L69t3yldClvj6Tcdj5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzlOT2lVc1FhVUJWUDJ0
            cG51dnhZd0tTUWZVZngwS3N6K0hKaTVvYWtFClZDQzlBVlJqbXNma0NvOG54bnJM
            UW16WHVhQzh5Zlc5N3BqOGYrVGFtL00KLS0tIHZSenhJTUJmT0t2aE9jR2loMjJE
            bWREdmpHbTFQZXRQdlVSaFVSRWdYcFkKotwiDiy8f4HdzUhUxBM7hNxFis59SGWA
            VGDuyhF1xdlH7XEdLqvhvMVulwLjhYTcfSpFZvNyUwdCu+WDtRdjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T06:18:57Z"
    mac: ENC[AES256_GCM,data:JyrAtIw1l7gj3T6lTkIDDRuDng7/l6ERlxp4+QPAAb1b9+G9D4DuFpM1+v/d3qmDF7l+gmCoa3Djb23gTB6dZFrBRCCjq+fZIpcqgOHhL8m7TiiK2ZgLld7O4PSpB+wbVmRbYPptlNePhTyurybeCFXUqgFZvWe9EdxIrPw3uz8=,iv:GyOug2NEU8LxgJBJ7ky61eGQ1oGpumB0copD+75ockw=,tag:9FbowOTwbV4sCBQNiGHjkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
