kind: ENC[AES256_GCM,data:t+0jU7Zo,iv:xxWMzPYGD2LY/onlieUkTjtDQ+YRtfgq8J1rNyNV8Xo=,tag:97NZpM4NMLXa2sD7s1B1aA==,type:str]
nfs_exports:
    - ENC[AES256_GCM,data:WkWuoBXCDldlVC1Du789qy3Mkoz0HHEQzykJWXozM9eX72REf2XncvoYix7U+M2VRoFvxRHMbUlcDrOzDPU=,iv:/SuSP+kYr8R/Lp4QtjlBK1KoXedho5U/kCFm/eyocF8=,tag:1t43ZC+u5X3IWxfCyOFIQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzlOT2lVc1FhVUJWUDJ0
            cG51dnhZd0tTUWZVZngwS3N6K0hKaTVvYWtFClZDQzlBVlJqbXNma0NvOG54bnJM
            UW16WHVhQzh5Zlc5N3BqOGYrVGFtL00KLS0tIHZSenhJTUJmT0t2aE9jR2loMjJE
            bWREdmpHbTFQZXRQdlVSaFVSRWdYcFkKotwiDiy8f4HdzUhUxBM7hNxFis59SGWA
            VGDuyhF1xdlH7XEdLqvhvMVulwLjhYTcfSpFZvNyUwdCu+WDtRdjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T07:49:51Z"
    mac: ENC[AES256_GCM,data:2gKDLhbn8uCzGiMQ3OAXiTUsT8l1OtV6pbWU73b45ztuIeGbsyekrhAA1CjZW3CQwKhpm+7yDGttpcuKXNu3UIMC/Htg5ZVDQJpfs7BgBe1mgzWI2c2KwA6yI7zimEx22DtBBhjhf2zOwdTuN7Rbj0c4rKf4kPaGjyes70my5U8=,iv:+VK+qoT5j7GAz3SxJ4DM2jFBl0wRVg4RnoOejLIm+lY=,tag:4/Q6qNrfhDkWNaUr1WRBMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
