kind: ENC[AES256_GCM,data:t+0jU7Zo,iv:xxWMzPYGD2LY/onlieUkTjtDQ+YRtfgq8J1rNyNV8Xo=,tag:97NZpM4NMLXa2sD7s1B1aA==,type:str]
ansible_host: ENC[AES256_GCM,data:UKqIcEFSElBiZ14=,iv:qYeObWRZPhxIYT8JcWFA9txkHv3xkwjKfr1UwZg14dA=,tag:5Dq7yR9QTJFWqBqzGKOLIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzlOT2lVc1FhVUJWUDJ0
            cG51dnhZd0tTUWZVZngwS3N6K0hKaTVvYWtFClZDQzlBVlJqbXNma0NvOG54bnJM
            UW16WHVhQzh5Zlc5N3BqOGYrVGFtL00KLS0tIHZSenhJTUJmT0t2aE9jR2loMjJE
            bWREdmpHbTFQZXRQdlVSaFVSRWdYcFkKotwiDiy8f4HdzUhUxBM7hNxFis59SGWA
            VGDuyhF1xdlH7XEdLqvhvMVulwLjhYTcfSpFZvNyUwdCu+WDtRdjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T05:14:24Z"
    mac: ENC[AES256_GCM,data:LUul2VmCFlWjjvmm4Vun4S6HJl53LumxWEilkFTKuSS7QLYjnS4AMfaeNCMA4uYF0N8ktol8b8RaRPhed3ZFhGefSs0n199tq59wIQTnde9jZTe/dqW1LIo2IUJT0M3m+v+g/Yq4WpyPFGzRLYV+ZBQoiha13PKGmMa3rhwsOT0=,iv:/5wjnoYNGPgs67eyRCDcRiBA1AMl5HoldT07KbazZv8=,tag:eFw8Aw135TZjiPZD3I/XUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
