kind: ENC[AES256_GCM,data:t+0jU7Zo,iv:xxWMzPYGD2LY/onlieUkTjtDQ+YRtfgq8J1rNyNV8Xo=,tag:97NZpM4NMLXa2sD7s1B1aA==,type:str]
ansible_host: ENC[AES256_GCM,data:X0oyIINCR5W0,iv:oUzeGNqYINPNEhopt6VrHs3Sn87XsYXu6A8NBswZFv4=,tag:1VyeuGfetnomS3WrkE5AgA==,type:str]
inet_device: ENC[AES256_GCM,data:3W1RTr5ZSGQ=,iv:TSVUv1hE4majKT/evwqE21B4AdLnOr1R45uX+FQ9LeQ=,tag:xYXbHZ2Up3Y8bDoMLSivQA==,type:str]
zfs_pools:
    - name: ENC[AES256_GCM,data:TSRhMA==,iv:kjURHxrsV/bR2kjNhrROOmzcfy6u1f/uQqm7n0+cK7Q=,tag:/jpbYUdhNJW9MtFFtLGURw==,type:str]
      mountpoint: ENC[AES256_GCM,data:5K6MCSE=,iv:HBYif0USdoakH/OW1yh+NYE9b1HPIRCyHvr5eekfTfQ=,tag:zzMDtWZAeQsiA7P1Hjyg9g==,type:str]
      devices:
        - ENC[AES256_GCM,data:B74jRYzFQM/asUmw7exr4M5OoBKnM3wnvprg4XC9WuG/X21Qaw==,iv:Gc1Y2dBr64uFFJGckkwoB0fLoLgqvsVJ0yHQX9VGExw=,tag:ipoq0PqbFy2frpgCZpvu/w==,type:str]
      state: ENC[AES256_GCM,data:TmCifxfAUA==,iv:zNHWFhjf1CQkEBICBDwk9plNuBzPvheC99kTy4ag0NU=,tag:mNJBcEM4uUEweT4sWTTXBg==,type:str]
zfs:
    - ENC[AES256_GCM,data:Y/r02KWtOsc=,iv:iHMIj+2ztLJgM+cGBFme5s5iCgRtOkybK5daobrNQiU=,tag:c/QvHRzKi+oIZBoZ96yjlw==,type:str]
    - ENC[AES256_GCM,data:Yje/RDtETruxLDDH,iv:LCIXuLhPUAukVAs7pi1HHwkpG4kF7NWLfY2cLeyQriU=,tag:P+4CZlClV14V/E+00Xmcbg==,type:str]
    - ENC[AES256_GCM,data:17dZyeSdcGktrw==,iv:kGpCX0ExzBl///BPeVfB/GjEPbkre0ue6+ejmw5AcBw=,tag:P4IUCFYh++zZhPeJFvQF9A==,type:str]
nfs_exports:
    - ENC[AES256_GCM,data:BkdzmcOokIZLTmetlk2NvF/Cfi5ASCOW/SWfBoCDi+/mX8A1t0LkfovMhAbu5+zvZLgrax/LCV0WhYULuviors/1/bc=,iv:x0TneTYycmh/0XiD+xnzFjW3WRkf/Fyt14p5ca8RPIo=,tag:k/Dreb734xCU5vCBnDSrbA==,type:str]
    - ENC[AES256_GCM,data:3UUBMgX8nKsaG3Ce/YgeqI8ihYAMtSSvhHeGso6hKSIL1swqvKZnDpkfMswom1BzklFGoxkAfYU8VMdHBrVRFdK5gc0=,iv:UgrPdq2ogMhf/qAgnznW+OHchxsgSq72K8x4Q7LVaNg=,tag:ym7EHmOfTnjVno4fgK4/IQ==,type:str]
    - ENC[AES256_GCM,data:8FjCqSyWoAA5EkOxAPlNrQu09ADkWg20TpVcNkouw4V/ODGmLq4XJxCF/u1F+130eMPKFyJM1FOuf6g3uGFyCy24nUc=,iv:rfGINflbGplR2gJzErfYLeRH3ZRded4itxnOZPqsJu8=,tag:7EjlJs/tqkScy6GSb0K0UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzlOT2lVc1FhVUJWUDJ0
            cG51dnhZd0tTUWZVZngwS3N6K0hKaTVvYWtFClZDQzlBVlJqbXNma0NvOG54bnJM
            UW16WHVhQzh5Zlc5N3BqOGYrVGFtL00KLS0tIHZSenhJTUJmT0t2aE9jR2loMjJE
            bWREdmpHbTFQZXRQdlVSaFVSRWdYcFkKotwiDiy8f4HdzUhUxBM7hNxFis59SGWA
            VGDuyhF1xdlH7XEdLqvhvMVulwLjhYTcfSpFZvNyUwdCu+WDtRdjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T13:07:50Z"
    mac: ENC[AES256_GCM,data:O8KdHdnOc3tSm3qJwbF8V5m8jOjkCgt6BaNGQ5Qj3UmLukmhx3odb8P8cuG5YmRY/rHBNl9wnGmuJXeFeSET+1w8rte2n0IvCau/EgQrraZCfSbkRikA07dMMAkHf3WA2xLgB8NJhu/SBRZllEnGyfKZHY2pmOA6/Tl0Qd/UQ8E=,iv:OBmOHbDBAJoEjSLTwZl+q+x6OYEIR9CRAzULXAX1E2U=,tag:mQ4tUpmF23hriiY0eb7Q4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
