kind: ENC[AES256_GCM,data:QEnnuKp3,iv:h1xuOI2c3QUKju6IaWdJA4dXdo1nHZGfCCaD9KlCKJU=,tag:NuXHzGc/gDU6zhC/C7dUWw==,type:str]
ansible_host: ENC[AES256_GCM,data:elqmvU4Fo+AH,iv:bZ9Kx0LH5+obokUt5uASrEtkeLm+MHFkrriSmrd6HU4=,tag:SGiYgwjlwq7JuOLnTgKfSQ==,type:str]
inet_device: ENC[AES256_GCM,data:r0e+NGXj,iv:q2y5mc5odrbBaboHdXdIohoA9iDnJeApNzK1xFk2Ke0=,tag:igzRv3w8Tdkr+6wi8fr+ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZmJnNUE3NnZFMkk0c2oy
            eTJwSlBieXZTKzRxTkNHU1NKRklyem53TERzClgwbS9aRWdGdnYwOUQ2djNDaUhG
            Mk5kUEJUTkdwTm9kTnd6S0FYME0yNTgKLS0tIDhmT25idXdzV29tdENBNFhhOTNI
            WDJPZnRtSjZEeUs4aCtLTnZNeTJoaFkKIY6zZPMhJH94SSd1EfQ+f9qEYyU0gwNe
            2nKEUARtpQVnG7FJrs0oNycH/TKICicu3R4MiHk6a123Zljhg+QWGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T05:15:42Z"
    mac: ENC[AES256_GCM,data:FxNk2LeC7rLKHUryHujax1s12Xx2tuhtxgjpLO/Dk3a6qnNIEgqNNXUXOe6EDb1pHlijcRV4qkfN7uT4TqyVW/QZWan1dSkySsEFte2dp8NWPY8LMVL4FRG8hlUZ0Uam2gw0vEmRYT13246gSRXaIOGqZ0xPmJTMV2a2JjYuR68=,iv:KAsg4qNtoRH2xBPPPh4cr8Ty7mwi94FEUI5afhiakNU=,tag:ypBiPRqck5/hoMh1u5L9oQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
