kind: ENC[AES256_GCM,data:QEnnuKp3,iv:h1xuOI2c3QUKju6IaWdJA4dXdo1nHZGfCCaD9KlCKJU=,tag:NuXHzGc/gDU6zhC/C7dUWw==,type:str]
ansible_host: ENC[AES256_GCM,data:J6nM0193VPQ=,iv:sLyhRhm4U7QXSw/2D4yNXygVekvp06m2zVma4BMjujY=,tag:PLv74n2p5pU+paGSqx3jjA==,type:str]
inet_device: ENC[AES256_GCM,data:WPTnQg==,iv:Bb2/q/CD8mWGEa0LM9C3/32Bo1DZXym6F3ilCtqsTGE=,tag:rXsz+Ox9BMhoGPqqId3tKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZmJnNUE3NnZFMkk0c2oy
            eTJwSlBieXZTKzRxTkNHU1NKRklyem53TERzClgwbS9aRWdGdnYwOUQ2djNDaUhG
            Mk5kUEJUTkdwTm9kTnd6S0FYME0yNTgKLS0tIDhmT25idXdzV29tdENBNFhhOTNI
            WDJPZnRtSjZEeUs4aCtLTnZNeTJoaFkKIY6zZPMhJH94SSd1EfQ+f9qEYyU0gwNe
            2nKEUARtpQVnG7FJrs0oNycH/TKICicu3R4MiHk6a123Zljhg+QWGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T05:18:09Z"
    mac: ENC[AES256_GCM,data:JGrQoAiBthdLz3sYkIGGhxsryXQlnTs3ekrNJHLrow3uWmyMX/ouEbFFAic/1kS4E+aqpEHAt6WDiPIw6tpwQuSUBGE9xbwzwrOQKKAJ0dr+g2E/b9ojP/0pGj4HdK3u34RZUaCwsafZQkiY+5evEyMDVgGSdeIbjO1VpWSHXI4=,iv:JxxuCcYrsItd/jfxDkB3VnlDSgVu54FmW3kQ9RTPEtQ=,tag:eXAoeeBrZ1IwJzAigIJzxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
