kind: ENC[AES256_GCM,data:QEnnuKp3,iv:h1xuOI2c3QUKju6IaWdJA4dXdo1nHZGfCCaD9KlCKJU=,tag:NuXHzGc/gDU6zhC/C7dUWw==,type:str]
ansible_host: ENC[AES256_GCM,data:X48im0dcZCab,iv:dbm8ovUQw+qAdtLXnHG1hA1/c0psq7RlYDExsUJzjTk=,tag:HSROs+jta5yMksP0nAKkvA==,type:str]
inet_device: ENC[AES256_GCM,data:K/PN0NjA,iv:j8w0RGyRwS5e3FJG8r2Qx1PgeIUhNZ9BeANwJdXRS6c=,tag:Tu5FqGC/0Dgc5oxCrCG3Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZmJnNUE3NnZFMkk0c2oy
            eTJwSlBieXZTKzRxTkNHU1NKRklyem53TERzClgwbS9aRWdGdnYwOUQ2djNDaUhG
            Mk5kUEJUTkdwTm9kTnd6S0FYME0yNTgKLS0tIDhmT25idXdzV29tdENBNFhhOTNI
            WDJPZnRtSjZEeUs4aCtLTnZNeTJoaFkKIY6zZPMhJH94SSd1EfQ+f9qEYyU0gwNe
            2nKEUARtpQVnG7FJrs0oNycH/TKICicu3R4MiHk6a123Zljhg+QWGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T05:17:50Z"
    mac: ENC[AES256_GCM,data:6vFaoBst5bHm/zfM0BVdU8OwvCKaV5b/JA81LNUptwLacGsR1LctJET4qwiNIzyRt7ID2mKe6Dt6ngk3XNbL15zUAJNY7gj2YOgZ3NQUlnf+EVwIVeIxIatmRjWwOLQ/JeS7wjdcLSkwKdRplWR6FoVrPFUghvdSeJF86Exz7+I=,iv:oVctuGMSnbewrBdNKpXUa+OqpMK5hPFj84JfaxYNPz0=,tag:65vuOmKSN+KJhdt9zdmjzQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
