kind: ENC[AES256_GCM,data:Cl3K15cm,iv:uWDQIDP43D8noME/Id3pQFpPxfPcub43gqpaI6TJd+s=,tag:K+/2B/1F1K16WoH/RaMccg==,type:str]
ansible_host: ENC[AES256_GCM,data:+soB+FL5KP0Q,iv:DNinAQ/037BqNSs9ya1uA4m20zHmnvtlFCcszUQ4f9I=,tag:52oxnbHRQXMTXI+WtMVqMQ==,type:str]
inet_device: ENC[AES256_GCM,data:rucrrQ==,iv:illXW6V5DR91Gw0gLfwXc/Iti+u99W10ZQjw5BThLN4=,tag:0WCNXpc7PUR5+hSoNOpmvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSjdsa2twYjNUdVRnSGIz
            ZDBKMy9pbnBSSjF3YXd4ZmhndS81NTl4alNvCjlZRk9wazByVHg2dUZDeUZtL2hy
            elFqL3MrSkFTMmN4YTJaTHBRRVVXTDAKLS0tIHp0SFZDU3JyelpOcTRyM2JJNVZz
            SHFkZmhYVS8va1BvQkRaZXBUelR5TWsKOlzNQxihXkgJrG9ztte0Cl2rwY/zMjEl
            /zhU2IG4LJdACWWbBTBeXvAyzJ2OTm8baAGyBJiYtu+moe/BjQiSWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T05:17:38Z"
    mac: ENC[AES256_GCM,data:nWv6glM9ydBc5E05XZ7PhQyz2zvqXHyKl26/EMcFDLVDUF2q9pHwY02CCi82H6lSqhCqG/QT5mS2bc8Bu6hhUgd2Eh/rVeugslbZ9B9m7ttdJTiYFZL94cKuvWANikU2YbAIqEYno0asbFof7ojCPpr48H4dZwpgJghoni7QMkI=,iv:b5GYl5hYSve6/EBmGO75S2i6dgHX3zFKIWXmYaMsB4Y=,tag:/J2WvN9yN8KTIZjlyLJlKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
