apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:iByiLbQTX2f1FMs8SXt3dOa2gcGC3RaMF+e2ekAn9vzhXvO2Of/yUfXSBhVwlwbdvQ7IMlk7kPjdEkST,iv:ncljKSS67Akko22W4VNSNaYkxFXHmGlwkKHjc9NpOPM=,tag:vJRb5wf4eKErngwU/PAvew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVXBPWFV5dXljOGRtMHNS
            Z1RtWHBsTUNXTlk4ekM5TjQ1SjB4dGtndnhJCmQwaEFyOG5qU1JOMDJkS3RVdkww
            OFMyUlZPdEFhV3hSdDU0UWlrUzl2M00KLS0tIG8rZ1UvaWxBZGQ5UmNtdzRBRHZZ
            ZW9PUkZ6RFYzbXNpMW0yL0ZEcHpHb2MK0Fuu4GHRj21Y1LD2XtXm4SrThuBGhznZ
            zUXpRZbca13wvVN7iqaePNlsUM3mWXu8cme955Mrup5l3u0H0hEXtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T03:18:01Z"
    mac: ENC[AES256_GCM,data:yHXLvrWTD+iMpwRbclNHSiX/tcveurptQZrcGsdxafXQP5aTrMZz0t2m2rG8D76emuIsl0/uv3CW7c+woopKV27OB99vwSoFLZCQwO3dZA2OikKZOl28MRPgX4NLw2RlTR9hAB5QwROCeMuP/vL2dDUnxd48rhB2tzltFoI4yzo=,iv:VAzB2WVz78OpKoRouZOkjsHQclFgxctwDucCUgOmpes=,tag:ZqRPVsi3jp05d+zYplMiFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
