apiVersion: v1
kind: Secret
metadata:
    name: nextcloud
    namespace: default
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:lm1yrQ==,iv:LZj6zKTrBMLbF4AfYFoLSeSA2xHvYLCxF8C/sa1HYzE=,tag:lxF1C035d6c/xlM7PTg/zA==,type:str]
    ADMIN_PASS: ENC[AES256_GCM,data:OEUM/sdCUG6vS08J,iv:CvfIsbgmY7RnBgWTixJ+C5B6EjxGX7PBSyR9dp3nCzA=,tag:2wY0K2sfI4hGvN8odA9aXA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:f1nzLXiyzAmjHeuXwvAEnG3R3Xz6CvJK15Sctncez/9hBQ2eig==,iv:rEvnTs9g0VZg/wvbMAPjrsDm1JdUwb8tcrFjNfrRW4g=,tag:h9wpuGWvBKD9jxwtXcJOUg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:9xSJeR475QNH,iv:e0xgLEE41vfbXsokG3fVoKESD9vkMU4VA/XkKdHRi5Y=,tag:RcKjOXiOwYGUUtMevIv4qg==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:/ESvMNk6Xs+Kb+4=,iv:5F/2qWWDd9Cgp3iCQ2worjnft2nrHC0ZpCZ4Pv2MaCE=,tag:mpAIGLynQ5WB3xRMSTxCVw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:SDeQec0Z2A9NRGGPCfI=,iv:3DUHKj/8HR7XGtbsyGXHV6JwmUUsXD8ybWeYfLd7DXY=,tag:YXw/swW0JMp1a2BnvCmMHA==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:aZ1CChS6LjbNBfdp,iv:6JInsPpouxPCqKWti7VKZv3vZeQJH17/DH7TH02g9uc=,tag:EBzYXhDr9VHevixPPe17xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T12:02:13Z"
    mac: ENC[AES256_GCM,data:64LZlvHY0V/Ri/vXx4gDrAlseIvEl7yEACDtnChDorRrOe65VV3YaD01PS/A7KS31S8HjJgU16VVzbpZ68XS9sMc1I00ujPUdPZraIuYf6feCgkamTm3NJxrWNG7920Mmmm7df4oqHm58WTCEC8G2QSo1C4oEtG1geytQ1wIBGk=,iv:wFazJ8APWK1b8CO5K6nfaSv7/De+10+qLDaxWV1HkE0=,tag:T3v0ufMsHa4044E39VOQfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
