---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
namespace: networking
resources:
  - helm-release.yaml
configMapGenerator:
  - name: cloudflared
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
