apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
stringData:
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:dXLmmrVqmbKHieuG0pOSHg==,iv:flb9xkE0BwFyQJ1ePFpqDOny/sYr5AFVz2YCdqJm8AA=,tag:aZfMwv1xgA0ZQUaV9d47TA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:n96ik5vr7ppAKvuXWExPdNZPu64+NGIKUYDgHNA0feQN/kVt,iv:uOuy6Jw9tH0TXzAhywNLUKcslqqKsl9Ma9AU+qUOOTQ=,tag:E2w2ynEk+btCiXqE+42RxQ==,type:str]
    tunnel.json: ENC[AES256_GCM,data:1vLWWgnCXDkLYJOLx44qpdShMh2U4NH8+q3IKr65SVQo3dgQizfAwEbEFXpRYTJm0SUoy3EiMly//LBI4Zqa7tSdGAKOpGtZ0y/mzbGCvcwP6/rLXZbI3yO1aSfOFHdc/MwLw8QpVTJeiOY92sEajoB4Hso65tKrm+JZO6cT9/jnSTW/Nc9eSP0JQ7Ao/VP1OBIcTtYjrxmW+CYjs9acndjrxSHSRwcPjwpIgf39IhY=,iv:M7VLpSksF1dECQTTPTduk7i0OTd7zVcJ+RCJTKeEvDo=,tag:TT3xv7us97FQUoelPlkprg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T14:31:54Z"
    mac: ENC[AES256_GCM,data:wlj2CPRPI9085ETKKaENDNmCQjWmP6jtfgg4EFFf+HxQyNBgNDNL24OlHpdiKA6LxTgwZmE6mbdJXYtuVvuRaN8jFhqv5d2TCbUx+6ct5DfpLKnC2kGLSbo49OJ3rHOO4wLy+4ItmnWDlPAsesyxOP4NGGyWSzZwreob8azsdbg=,iv:kpfd3qGbaLqCArokGY/EHf6MK4+kGDDtgVrdCTiIo7k=,tag:WK9BpSb32QDPP77k984fOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
