apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
stringData:
    tunnel.json: ENC[AES256_GCM,data:WBImFcFnIA6RVwVRZQZ+HUdb63149UheHieJrBsAnqACs2sgSWbnms5NBXWYMByyxHhAkPVCfwaD2rpw6IJ2Kk94jZziLVXlhOVwA0bl7K2yhDvOJFAYjHzKMw7PjtyrGcc3uSHVtP0L7ewgIg/Z3xsX033Iik2mhARIrGC9dg9lkCKvTza6JRxmc8fbvwfWpoUQmTdDLSqly27tJ16saPuof7fW,iv:KyRlW8h9WsqNlB4qFuEJDBLsRSZhb6UZHzEK789FoUI=,tag:H41uDYd1oRAgMapCCyW45w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZEtEYzVhODdxdDhSRTFN
            WXE3UWx1eUpnbHdZb25td0c4emtBSisrZ1U4Ci9nUjNyeitjZE1rUWNPRTVJZUJt
            dmhlQXRoK1BXZmo2cDF1OFIzMHd6ZkkKLS0tIEI2RTdrREY1cUpTajNBckwrQ3hv
            cXRuRE03aFMrM2ZBQVVPRDRXUHZPazAKVcttirwYIW20XGipuRqdwZlsKI9fyCNs
            JXDLN34K8boXH3rt4mV/quhsIT0oRugqf0tuze8g7FmzasijV1/TWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T16:32:59Z"
    mac: ENC[AES256_GCM,data:Di3I5q9hDMZeePjAAd2eaECeSNp7Gc87/BUr7zINHmyXLrRaIpyXw2QEBXHgkFfnYlTVhgme9oYf2lA0tT5Iw60ukKvBXa+I1M/yj6O6vUqHnSGCh1n0ncL2dZhjIEuicDbkk/HuOEM0QO76yG1IDBKHLVRWkBkb7BUDx7VqaV0=,iv:O6grOYp8Xj4d71a8sL9r6hs6CWNNUIA1krVb5eBQH7w=,tag:k0E14xFTA0uflsPTfdAnEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
