apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Cs3nKoa4RqQQLZhUdEtAzZTMkhjR9W4d4GK0brt1COumvdmiasAhYA==,iv:1cKEU/LOvE5SFEz0S6ZPZXVqQe5G8FJO2lns73hPb6Q=,tag:1Q8em1ffOPAGfZTUrsNyXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVTI5alpocUxOeHE1MTRn
            L1c3eG9uZC9sUmVTTEh4MU5UNFhqQVJzaURBClZMSkNHV0lZQTB0elVob0VGT3JF
            V1ZkK0Q0R2xEODNPRFROdFAxVFBCLzgKLS0tIDBmT2pLbXFvRFpiREg0M05hLzdC
            WFJ4NSsvRWlHTncxR3BSSmRKaDU5QjgK2Alssa2kFibEBT2p3+KejXbXfXc3KaW6
            CfF4OcgzT2B6Eg22uDjosjD+TZVhsPycHpDAq+dK/aD2ZbDwh7Frcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T19:12:56Z"
    mac: ENC[AES256_GCM,data:240DtjmzvhCxrz1h0iTVTPPqGVdAewWRlEPG3XtCmednLf5LGeOJNc5S4gqoVKjTMD74qZJr2r/G2t05v3j/21ECBowlF/545CM39ZnLHbP1U8yuSIh0iIJqtHr2qnjf/ovJIusQZldPG3wd0LVRheBsDg4RjYnbTxmSNhWu4D0=,iv:2HFtZk+Q+aY1Mp9nU3/iXciWEMmH1nLEqhLG7Pklg9o=,tag:nbHD2imWsWCZIOgSzxcB9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
