apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gMMOF7/SFvU=,iv:dDvCo0TEFlX91YPiqBWHlCo+DFw8eJUikMi3s2vuvNY=,tag:xtphNTilGzXmB5XZwOtnhw==,type:comment]
    GF_DATABASE_USER: ENC[AES256_GCM,data:+wTxQGTZQg==,iv:3ulqRHt8LLZc2qhLHmxwjvogqaq/6b5mGmNpy095GbY=,tag:cd+kRPgKzPJ+RoPkuuORGg==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:5HUrtbPHyp3pQo4=,iv:UgKkaftHOjGSTNmauM7BaZ+IqKc/qtGtbZbo4JGkT2E=,tag:9x4WufD5N6Nau8rhUBjSFA==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:a/Y5xHOQrSgYMmmmaMI7kvVxn8kddOQZmBTLaI9TyaVj4a5bJmunwRdw,iv:O8DUxJ29QIp4+q2w48lmWM7dmNm56Gjf4H3nLUpgEps=,tag:MYOjQ6uoCpBNcw3MqK2lCQ==,type:str]
    GF_DATABASE_NAME: ENC[AES256_GCM,data:aQlLy3OrbA==,iv:1kzLhos3EKw7jdi0F+yJYS3/pCmil6ARwNZcmh9yovY=,tag:gGxGKaLgYXw6gF8qfedpfA==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:JjB5yzTCqg==,iv:uL7DVwgsh69mVrcrdAivM4Ixc5SKKRmMzcjUnaCYDt8=,tag:wo/vHkyzAZAxgK6lFKFbaQ==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:YxOYzqGXe1M=,iv:xeo6C0lFO6T86ksw/eMMon1JIj9+lwvmiDuMiTF+2Cw=,tag:GgiZDGM5QmV9rSKDt9bHLA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:JIgiWDFFVIp/JwCd,iv:24CiymnoXizy3oz3h9POvVjF4nLjv2z4YbuC5qQVYlM=,tag:uAz+s0ORFC3tNDtfrHMBpQ==,type:str]
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:mKzZoA==,iv:fyrseWyCkY//Xi8X47zTQI0vFC6g8Ozj+PTMAZkTZBo=,tag:xW2Y8GbTayD5zHtR/K9M1Q==,type:str]
    #ENC[AES256_GCM,data:C3gdi1xEgSvfdyApSNhMkW43B43hVwqGQYfThSdbz+1mgy5V9/t0hRO9HydXhALl6QQCIMiFAbCH7EukIZHNuyAwCOfMIAKBQhqLaNSSymAthpjdfrUyXW4=,iv:fuFRGtQWZ5JSxzTzdpw8Bc6C/9q/mwzK4JopWhL4u08=,tag:xWHviOXghTfSs/Ru6N1O8w==,type:comment]
    #ENC[AES256_GCM,data:F3ev6iABD5eFFdpnVQQ=,iv:dXbmxWvQNxqMhq+b5YuiHL/nEl7JruNVfhfMgTL5fDU=,tag:Wwl+5qKFIyfjt7i6BirEcA==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:9Fx0wpeutw==,iv:mPFOsJPOy7BiB1tfmO8b0IMMnzWGN03cYugWNbusb2U=,tag:wKCgf2EdTzvqllLWP5ioJA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:JPuxyaU+L2h21hgd0oe1kFaixSliwix1j8V02318ChbMEGbkbg==,iv:myLiWvsNs0QUR/h/diJLhWLlUbd9HWBPOamiwSZweHA=,tag:6LgESjGtEeDNQR2sLnWZSQ==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Y3LriITkJvKJbOg=,iv:Z4DCnhIHPnzyRowqYuPAQ+yukyT7n7u8m9VOHoaJN2g=,tag:6Q+7E8OMGfXbRAHCn9ySpw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:tu8Yg3PmTG50/vM=,iv:GrVC2OZkuRyI5rGHgfkPDfGMTVSEKTuI0Jdv5foSoR8=,tag:JMDYKpP3TndBlNRfJ4P5qw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:6AAUhv9GDA==,iv:prVvcg2niGZzZ7LwlO9/ucGSJvN9Gepk0XZYLN1kPmU=,tag:CNpZEOVhulOVSFgNSkJLjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T03:26:56Z"
    mac: ENC[AES256_GCM,data:/NRtr4mKmQaDYxyzw9DqL4GeWN+DLJyjglQavj4ugyvVYmR6uOn1Ke2/7xGGk8qdu2GWrIQth1F/7iKK/kihYsKeLB2LWZipH1Vd5YgzsNHUgCaeK5ZLTgYF6CQZhuVz6daxt4OScp3n1Mv6DF+4EMV0FzNuVQKyeLrx+xE2ftc=,iv:zs4S8Q5wwiVrKYwqDDvPToNM6QJDINB4R7ciNKTmwsI=,tag:LX2O7brlJO8NsmvlU7IAXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
