---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.0.24
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  timeout: 600s
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # image:
    #   repository: public.ecr.aws/emqx/emqx
    replicaCount: 1
    recreatePods: true
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_CLUSTER___DISCOVERY__STRATEGY: "manual"
      EMQX_NODE__COOKIE: "olympus_mqtt"
    service:
      type: LoadBalancer
      externalIPs: ["${EMQX_IPV4_ADDR}"]
      externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.${SECRET_DOMAIN}
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          haproxy-ingress.github.io/proxy-protocol: "v2"
          hajimari.io/appName: "EMQX"
          hajimari.io/enable: "true"
          hajimari.io/icon: simple-icons:eclipsemosquitto
        path: /
        pathType: Prefix
        hosts:
          - &host "emqx.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - *host
    metrics:
      enabled: true
    persistence:
      enabled: true
      storageClass: ceph-block
      size: 512Mi
    resources:
      requests:
        cpu: 10m
        memory: 150Mi
      limits:
        memory: 512Mi
  valuesFrom:
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-config
      valuesKey: admin_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-config
      valuesKey: user_1_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-config
      valuesKey: user_1_password
