apiVersion: v1
kind: Secret
metadata:
    name: emqx-config
    namespace: default
type: Opaque
stringData:
    admin_password: ENC[AES256_GCM,data:HMCgPg6pojSkWtU=,iv:3A2kQ9KTyl4sI2InQIqPrAJ1+YCKu7a4pkrKZuqXsWg=,tag:ttdI1W2qrRVilF/7E8XWcQ==,type:str]
    user_1_username: ENC[AES256_GCM,data:bSnAGw==,iv:Oryn4F4YBNSxe3y0Whl/d0gurjqbgVu2FoDBCUTRKFo=,tag:eOhmpuC7VR0rZmcsoBTfGQ==,type:str]
    user_1_password: ENC[AES256_GCM,data:8e5nsPPH9AZPjoQc7VQ=,iv:dt6IGqCE9v/iPY5rnWIPzE7WGbU2NuDLzAxeuL5N52M=,tag:kdn2kfiAbavj8p6/ZFl2iA==,type:str]
    user_2_username: ENC[AES256_GCM,data:DzzP8A==,iv:s69CaeaU25Khk9ygsiQKwD3LwlrHXA7kamvlbEMP6B8=,tag:oRG18wBz2KieVMGxdIDTsA==,type:str]
    user_2_password: ENC[AES256_GCM,data:lcRoMPKLC/pA0GJwFyw=,iv:+mjo29L4To8j9CLLC8a6RIoW0jtOpQmxvtODtVzaT00=,tag:xEhcSiOudmtmQ6/siwRIYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T18:56:14Z"
    mac: ENC[AES256_GCM,data:lFq/+TOXLk+7qtyULEDxVxJXOrk1SDQEA82bsiBAk9YkzKknV9hDLV17nXXvFPGIB9YR+BwUkP18SR/zBfh4r3q6MRrjBlfyVMEWrvMiYiNcNX9gbbX1Jl+az4dgESnQAG2v9svVisu1g5h1vwrRF9L9cR6ub/Zm9ZiY+efF+l0=,iv:jDgGG/dTHhM8hTBqIFiVjGqwhWXstsahEA4DZNEs9O0=,tag:brnrpXVar98S7LGN1s1K8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
