apiVersion: v1
kind: Secret
metadata:
    name: postgresql-init
    namespace: database
type: Opaque
stringData:
    nextcloud.sql: ENC[AES256_GCM,data:UW2WAQHsp9DxA0jZfd95+ZSn6ZDPgeyhMYoEKb5bHm0XP39PRV7AXSIwHj4C3ohmOIL5EpzA3yMknmipg0sHTdp05gRzNO34Spg2F5TXY6TfDqUffF7KzViZhKagHZB9JpoK7vgHuzXPd4cI6nQnxKsgd7CtjD480pv5NMQ8YpC88yjh5DgS8L499LGNAlCBtbGFPJeFZNen5+AbbQiErio=,iv:e9aMIz7EhL0xVb+98dKkUelEW/1TNGmqReFPKWWKm4M=,tag:maLHE01YQJRNgKfLgiguLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T16:06:03Z"
    mac: ENC[AES256_GCM,data:WNVGRGj7AuTDQEgeUTixYJM5jhJGQ06sjweMI/0ffZd1YTp4O3KIDFhMgS6Pw22eLLUd7SY9eXTCEcl063ahLb0PLAUVxDCcJUPJGoEm/T4Y1PHgmp9OhqyzkDZ7yqYcADjhPwVpAtW9/XxgwGi/g8QcNAj6kunyNosa2H7eKsc=,iv:CfOMcRrpy0Tf5gh+Jf4C5ejpS0oOzIpLhNoR9HPGbcg=,tag:QAy5bLgjVw5q8rwnBxQ5RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
