---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openhab
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: openhab
      version: 3.4.3-rc3
      sourceRef:
        kind: HelmRepository
        name: olympus
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    #imagePullSecrets:
    #  - name: github-pull-secret
    image:
      repository: ghcr.io/kilip/openhab # {"$imagepolicy": "flux-system:openhab:name"}
      tag: 3.4.3-rc.3
      imagePullPolicy: IfNotPresent
    openhab:
      user_id: 1000
      group_id: 1000
      timezone: Asia/Makassar
    persistence:
      userdata:
        existingClaim: openhab-userdata-pvc
      config:
        existingClaim: openhab-config-pvc
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        # external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hajimari.io/icon: video-input-antenna
      hosts:
        - host: &host "openhab.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

  valuesFrom:
    - targetPath: openhab.cloud_uuid
      kind: Secret
      name: openhab-secrets
      valuesKey: cloud_uuid
    - targetPath: openhab.cloud_secret
      kind: Secret
      name: openhab-secrets
      valuesKey: cloud_secret
