---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: openhab
  namespace: flux-system
spec:
  image: ghcr.io/kilip/openhab
  interval: 1m0s
  secretRef:
    name: github-pull-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: openhab
  namespace: flux-system
spec:
  filterTags:
    pattern: '*.*'
  imageRepositoryRef:
    name: openhab
  policy:
    semver:
      range: "^3.4.0"
