apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Ba8I3CTPmpqdh9Vxwc0=,iv:x6qpZ8/4s6ejgxj+YeR8E/A8BWuH3QN3p993oDexroQ=,tag:g0X3ezOgMrDj8cpGB2iIPw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:b6WYd0pa89DSEIeCXQcopHqEEvcCIpLFhitdsa9hKu69i0okFg==,iv:va2+x+9cY5yvGMpqJ44z2qX6FiMtfy9Z2A0cMtxnXfI=,tag:HGROoM9El48vl2uSfdf1XA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:orAde7mNskYjKkj98YsDmg==,iv:Ng+GAwAuUjaTG1DUF2AkIlpfNLaIWRpn7jiO9SPdESg=,tag:AkshEjSqKFm9rwNbBob7+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T05:04:29Z"
    mac: ENC[AES256_GCM,data:0nd0/D9PvG6XDiexyHdlwqvKerNlBnJKa1XVi063GiHYhyK5ElMWRVwOhZYJMBorH+nHjQbun7hJX3NGevmlPpSxeRQJW+IZABxMIPXjKeT7Sv2d9DevozvPTnERFi1ydSMWExiIWtIqk3eaaUwukkBovpnunDoC3l3XLVy0bY4=,iv:aW0vCi6MoIIlwOqatET2qpuJ+OrmFpoUbxXAI10ygR8=,tag:HtuTm9fCvTnQ5Xcaq9gWaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
