apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: filesystem
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:HbOqiA==,iv:h45sLPmVSUbuIL4LhBu8GLns53+2P54Pgbyc0CyhEmY=,tag:3GAOePrm8RvKR2Ny4QOemg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:2SIq2a3jOhrvVJrS,iv:d5AJLFgGI8iv4FABrq8ldJQEniefgrepW1eaiAvpb5o=,tag:dv3Aiu6dCABigs/XWF5iVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T00:59:41Z"
    mac: ENC[AES256_GCM,data:5UbyBx1ChnIORbdq7GTL4/PAaQAMsx0DFpOniQnIcGGaKNalfOCZ2T3wYC6QirN63LMnpImtzMxm2bHATZmMN1med3zup1Xd6Pa2bP0NlPzs3LvR1twdTF928zy0vg7SFE18L8HQICodsj8tTFjuBJz8F2oEHp4Hj0wLYwcBAfs=,iv:zg3bB/hwTGJsdV7fLVgVk0iqv/R3lfOfXPhMUYTC2eM=,tag:Zd5NcFiFvbSD7X3mjIMQHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
