---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./nfs/ks.yaml
#  - ./rook-ceph/ks.yaml
#  - ./volsync/ks.yaml
  - ./longhorn/ks.yaml
  - ./minio/ks.yaml
