apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:m+0YvqUCV9eBxMg0lOs=,iv:CzD7drNBiGkbNnbMO0n2NMw1dJsLrsriYLVulLAggTg=,tag:m+7pam/a3nHkpyobNg3+Sw==,type:str]
    api-key: ENC[AES256_GCM,data:PFBk2mqrB19HyXsKHRrQtrkUvtO2ISiT7wsdUu8s49o/xmvL6g==,iv:59OVQi4M+AddkylEPGQxd1Z/XIPTixfEQ5hhUctMAiw=,tag:P7TxPAiPW2epyvLpY3YaYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZEtEYzVhODdxdDhSRTFN
            WXE3UWx1eUpnbHdZb25td0c4emtBSisrZ1U4Ci9nUjNyeitjZE1rUWNPRTVJZUJt
            dmhlQXRoK1BXZmo2cDF1OFIzMHd6ZkkKLS0tIEI2RTdrREY1cUpTajNBckwrQ3hv
            cXRuRE03aFMrM2ZBQVVPRDRXUHZPazAKVcttirwYIW20XGipuRqdwZlsKI9fyCNs
            JXDLN34K8boXH3rt4mV/quhsIT0oRugqf0tuze8g7FmzasijV1/TWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T19:12:56Z"
    mac: ENC[AES256_GCM,data:6sqqFC1GA+7zknawB49yCXpSywlamHet9c5YFQ8vsuFxewbLcGGayQpmqd4lIvtnuLHlOM92bp/3pUNAhiB2dPznBeisbnw19T+CqfAswXhfSdtRY6CrLDBipgYdD7ZIWGJ6/2b/HXnHFAevkEDj73+KhwJLXQQUrIBLZcylH0A=,iv:NxdEkDSN+2Y5RlhXt0B3ZRljPUc4NZLsHBmuRBi3+c0=,tag:ZuHRIWmQef7yAGLU5BRiRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
