---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: influxdb
      version: 5.5.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    auth:
      admin:
        username: "${INFLUXDB_USER}"
        password: "${INFLUXDB_PASS}"
        token: "${INFLUXDB_TOKEN}"

    persistence:
      enabled: true
      existingClaim: influxdb-v1

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:influxdb
        hajimari.io/info: InfluxDB
        hajimari.io/group: tools
      hosts:
        - host: &host "influxdb.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    # influxdb:
    #   livenessProbe:
    #     enabled: false
    #   startupProbe:
    #     enabled: false
    #   readinessProbe:
    #     enabled: false
