---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-v1
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
