kind: ENC[AES256_GCM,data:t+0jU7Zo,iv:xxWMzPYGD2LY/onlieUkTjtDQ+YRtfgq8J1rNyNV8Xo=,tag:97NZpM4NMLXa2sD7s1B1aA==,type:str]
ansible_user: ENC[AES256_GCM,data:tW5hjg==,iv:tDNV7N/RBf3QIJ3/Qo9z19jVxRfQF68tqsBaROYNc1k=,tag:Ea9hPE6+xcfXJ6ZC6OaL2Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U4Q2eKsfT7vRBpM9,iv:0nhsMdQRP73aYuvIug+csVGoK93r4F3EjfW3JZq+0DM=,tag:FBJD1ncvxXklWBDQOLfV0Q==,type:str]
install_packages:
    - ENC[AES256_GCM,data:QtdHZ42bPLtJC0CEN3sW,iv:1FXymlfRuZW9DrohIOzgNxEGIsdV+/nV5xpxESxeuxM=,tag:3v9g/LcdVBNeoZf9vgEVIA==,type:str]
    - ENC[AES256_GCM,data:mhouhA==,iv:8FjsD1CNGfbkpOvAqUy0SCBJYNlHd4oheoicQZ6rhmM=,tag:oaig9m6SxvVUHraZcN8xOw==,type:str]
    - ENC[AES256_GCM,data:PtYr,iv:7Up3Owg+/E/lcXx4o5L1SxXqur8Ik18blFZUcvSWaNg=,tag:dBmEU725x4Jf/+Cu+UGImg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZzlOT2lVc1FhVUJWUDJ0
            cG51dnhZd0tTUWZVZngwS3N6K0hKaTVvYWtFClZDQzlBVlJqbXNma0NvOG54bnJM
            UW16WHVhQzh5Zlc5N3BqOGYrVGFtL00KLS0tIHZSenhJTUJmT0t2aE9jR2loMjJE
            bWREdmpHbTFQZXRQdlVSaFVSRWdYcFkKotwiDiy8f4HdzUhUxBM7hNxFis59SGWA
            VGDuyhF1xdlH7XEdLqvhvMVulwLjhYTcfSpFZvNyUwdCu+WDtRdjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T03:49:12Z"
    mac: ENC[AES256_GCM,data:HZGjuFsbX3uCc0cWwvEXERHR1Jhuf60BVoUu79aKJ+I0deedcOyG4VQmDq42i0r/uFrIw/wRM24V0oAD64h+3Fhihe/4KOMKuDfpiRuGJTX0TjZFGIfeUaq6IuoL23D7N/Ciln0x5iOXf+glASA5jaCpsXk9ai/6Wg0X3rZQhqY=,iv:z0nmKAwPrjh91TXdXKhguzmt5qCHqJDkvqF2u3Putw4=,tag:T2NBBAJ1nn2xSz/nbGQ7QQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
