apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:P8gMI7WzWDgkeBpfQDuUwwPTiUMotvPhfjlQs8kZoytu7a8YRw==,iv:jEwO3/etCfZpRqs0VXjjSsFY1j+S2LiwlRdEy6cBlbs=,tag:z1dEMqptfNxN/qrfqkv6zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK0JRV1BUZkNUNkI1OEIv
            OXlwYVROYm9QNXFyRHJReDNUeDZxblh1YVhvCjlDNGc1WkNiWHJOYkNKQnQrNStU
            WGtLZjUrWk9COStQN2oyakFRcktTa3cKLS0tIGhJYW9yb3I4RzdTWTJQbGk0ZjdT
            aC94ZWFlQkJ5cGtzSVNRUlRhRXdjU2MKTVHYpTJeBcOQrVkHmn4RJLLuvt33JzXP
            BiSU/dR5EWk3czdKtY69r+5WoAZ3HpmqVtE5lwQJzZKSWU77i1EXNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-14T19:12:56Z"
    mac: ENC[AES256_GCM,data:ARbHdaoOlR5QudV1B8ybKDUQ2o8/mYHQppmWnz8hIvLhqXlE21TT4l3r8d0Bu9A51o5ZTN7oWYyZzjY/dqNa51oRvH5qbKjX7jwdhYFj9G3uV8NODCB7tTDmGRrgR66EZJVtRO+Udp88swB/nU/h7/KOo3Mb50imWmIdE4mxEBQ=,iv:62PTOl/CX8xoBqNE8jM9uayeEZE8xKe+NO6h2T5MzqY=,tag:sAKYBZji6Dkw5GRraLGTtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
