apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secrets
    namespace: home
type: Opaque
stringData:
    dbuser: ENC[AES256_GCM,data:B8R96aqYemot,iv:XTeY+6v7FkfTwa1oxHk7XAXbiD72gF9KaRubYz4Mkfo=,tag:viCZRYtKbvpRpcYy/Ulh7w==,type:str]
    dbpassword: ENC[AES256_GCM,data:swD+FkqYdm4vlS4=,iv:p6LMbpxRy8ivEbYG03sw6/+AaC8uUwnUvmWeFOQxtlE=,tag:BKxdF46OzR1LIozjsDShaw==,type:str]
    nextcloud-username: ENC[AES256_GCM,data:YKJsUg==,iv:cuYlOxJm/xcvB5WDLBi1Dft78EUx+v7GbEoU5XvJePk=,tag:zXTUt7JiHOARZL6kvXWRLA==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:dzytsS50VQSE8EwQ,iv:8MsP6twiXztzvLPrtETl6GLpTaaoNiGfRr7CZn4Lad8=,tag:QLT/o3aBWp9a6HrrL738sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T11:05:55Z"
    mac: ENC[AES256_GCM,data:p4cRb95K5YRaF5UU5iemz7pIr3k5GHML2lyr0Z6si5laPuQPtr0i/iqQXkpkAJj7ow4r7GFzQOXsem98ZlTotuVUJ6y6x/iIx/ciIYpeSw34YMmcbEwurhs+xlL3OGRSx6L9CX6M0ojn+h5wYquJMEy9S4a9rmA7y0bztjYR8q8=,iv:K+elXc23BtfkdqDRv+p9uiF8hnJx645WDVvzfKHn7o4=,tag:uwnyHtzdU32sRsO9SJqdcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
