---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloud
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 3.5.10
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: *app
    image:
      repository: nextcloud
      tag: 26.0.1-apache
      flavor: apache
    nginx:
      enabled: false
    nextcloud:
      host: &host "cloud.${SECRET_DOMAIN}"
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
      datadir: /var/www/data
      extraInitContainers:
        - name: wait-database
          image: alpine:3.17.3
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - -c
            - >-
              until nc -w 1 -v $MYSQL_HOST:3306 || nc -w 1 -v $POSTGRES_HOST:5432;
              do echo "Waiting for database";
              done
          env:
            - name: POSTGRES_HOST
              value: postgresql.database.svc.cluster.local
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array (
              0 => '10.0.0.0/8',
              1 => '172.16.0.0/8',
            ),
            'forwarded_for_headers' => array (
              0 => 'HTTP_X_FORWARDED_FOR',
            ),
            'overwrite.cli.url' => 'https://cloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
            'skeletondirectory' => '',
            'trusted_domains' => array(
              0 => 'cloud.${SECRET_DOMAIN}',
              1 => '10.0.0.11'
            )
          );

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hajimari.io/enable: "true"
        hajimari.io/icon: mdi:dropbox
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: nextcloud-tls
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgresql.database.svc.cluster.local
      database: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: dbuser
        passwordKey: dbpassword
    persistence:
      enabled: true
      existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
    # this seems to be required for nextcloud initialization which takes a long time
    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    cronjob:
      enabled: true
