---
- name: reboot
  ansible.builtin.reboot:
    msg: Rebooting nodes
    reboot_timeout: 3600

- name: restart logind
  ansible.builtin.service:
    service: systemd-logind
    state: restarted

- name: restart tlp
  ansible.builtin.service:
    service: tlp
    state: restarted
  when: "'tlp' in ansible_facts.services"

- name: restart networkd
  ansible.builtin.service:
    service: networkd-dispatcher
    state: restarted

- name: restart emqx
  ansible.builtin.service:
    name: emqx
    state: restarted
  when: not ansible_check_mode
