---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-v1
  namespace: database
  #labels:
  #  benji-backup.me/instance: "benji-k8s"
  #  kasten.io/backup-volume: "enabled"
  #annotations:
  #  benji-backup.me/fsfreeze: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
