apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
stringData:
    tunnel.json: ENC[AES256_GCM,data:8FE6oFYuWVCW0bL9Ps3aehYCd+u7afj8p5nLmsXDF/TZDiaEvsUtqotTpZ2u4asqUjqOrwgry0WuzjFxf1C3tX3qWWLv1a/2h9q/If0m96XHGASnI0xfvhN4PDlQr2d9QLDVO8prFshvUTCpBEKMh4j007SG2A4H/+oMbeakN5t+OmYJBJRsnYIKTXOX8/rdLjzPX9xNHhc+384K2ZSTKAf7SIRfx5dbznk8D9PJWvg=,iv:Bhgz8fP1qAmhrAkguuRHpBiorU1bV2qB6HEh4vQIf7g=,tag:0z8HDHHLYxqOirt84lG27A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZEtEYzVhODdxdDhSRTFN
            WXE3UWx1eUpnbHdZb25td0c4emtBSisrZ1U4Ci9nUjNyeitjZE1rUWNPRTVJZUJt
            dmhlQXRoK1BXZmo2cDF1OFIzMHd6ZkkKLS0tIEI2RTdrREY1cUpTajNBckwrQ3hv
            cXRuRE03aFMrM2ZBQVVPRDRXUHZPazAKVcttirwYIW20XGipuRqdwZlsKI9fyCNs
            JXDLN34K8boXH3rt4mV/quhsIT0oRugqf0tuze8g7FmzasijV1/TWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T07:17:01Z"
    mac: ENC[AES256_GCM,data:0GLeH4L4vAZueoLvzY8HqFGS/h+S5wmKpzsuv4oKGC07Zqo1N2gFhWo7MZrEE1WMWg6DHFSjxUqjAXchrrGSMt3XCHD5uArXB1+msQdzD5pj6TOBRSf3qhgZ6rIKc91Uxpp+C0TO+uh3XjO3Ujz75mKa7JXo/vBvylU3yjQABkg=,iv:LGm46uQ3yQudYB8o4+CUOYEkZjfbKVbiCIFBQN2PDfo=,tag:AlGDwWkJID0bD9ba2fC6jQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
