apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fiq7LnCr7fquAJTob96i,iv:5YmdewV2yFLEpU3sIXuhdmW8VkiuHyKX1nGKie4PxEs=,tag:/wcbwnxh6CXCucVrmCHihA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVjpgCRnqcUITmaGlKY=,iv:s5J/uZwgGep7LlrvgcjF7/gfE7knRZoAEMScnFQu590=,tag:3WtmDivtPs6TzoTDjPoMlQ==,type:str]
    CONFIG_NFS_SERVER_IP: ENC[AES256_GCM,data:etRq53ejhJbN,iv:Twu8AbJJ0SCzV8rTNrxxy2jx1qyKPDPG/mzxQnSmpmA=,tag:usN46p4unthnq4NKRk74xg==,type:str]
    CONFIG_NFS_SERVER_PATH: ENC[AES256_GCM,data:fHtIU6W4nHV0GuEFyA==,iv:MEFEHo23qZqFWodyF5ietjjMnpmFfsGm/u5VKcwrB8E=,tag:fdsrgzq0TKIZF5eTKoLfnw==,type:str]
    CONFIG_NFS_BACKUP: ENC[AES256_GCM,data:nxFobWuwGeCgE9uLVpY0GSHYZPqRiyQIx3K9xQM=,iv:K7YIdPKTNuOQnkmCjkyWL9C5eFGCfLMmOeatgSU0tXc=,tag:3X2gm939IKqstGwYs0y5ow==,type:str]
    CONFIG_ADMIN_EMAIL: ENC[AES256_GCM,data:x9ZNDo5HWkF5nSIN1i0=,iv:FeCW90RUFoya0t0azabUT1IjLZekEMzwhKpsmIPevLo=,tag:0R79x+q1tPTgj4xXYsyhtg==,type:str]
    POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:Brox4tpOmMdXRZs=,iv:OVYeKaO4ome0KqT0+iXmN3iMT1icDnsWPySCB1QN7bI=,tag:INZiCNAXHG5Mmvld0dQ3XQ==,type:str]
    EMQX_IPV4_ADDR: ENC[AES256_GCM,data:bALBNE4Y+G4qmWax,iv:lRPkExShjKvGNpZRqFmi9L6+j+/wvuhGhp+BFn2uCRw=,tag:/eljq9ovilzJOynG5GZMBQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9/GGkYMILZaCOmzMd73oClwakcY=,iv:vlTOUUN4FKLpg3TLedBI3LkF5Q1jyngB49f0gf/p6KY=,tag:sNxNQfo2FuXesVWcdOFzBA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4lbfhbMBDz1/v6mohzCXnw/hHjRx1ski+rS4VhYtkq3Z/jGr,iv:x9mA+Wg40IlT4qyxhRMAzoYjhbdMVSHs8WEzBFlF4kM=,tag:ySyxuHedQkfeGujpydcb1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-27T16:39:46Z"
    mac: ENC[AES256_GCM,data:q1tuPmNSO/A0s9lCk3X5Gs8XYWW5gopogDJCkGjacot1i/pCjrrPLpixiqUrZxN9ol3ZEAPf10xnofzawa+7KLRsZ10cQ1EXI5OVXRRf4KktH5Q2A3/6VSRVoA7FFr6+/p4pT7scvQeWIaGf+k8aYXQg6WDJupvyIsF2InxXz0w=,iv:O9f860mvZV0NSmkUl3TAcsh43gLrtWKxuCAz9gPjbxo=,tag:81lceBm8TmDkyH08dJ422A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
