apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fiq7LnCr7fquAJTob96i,iv:5YmdewV2yFLEpU3sIXuhdmW8VkiuHyKX1nGKie4PxEs=,tag:/wcbwnxh6CXCucVrmCHihA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVjpgCRnqcUITmaGlKY=,iv:s5J/uZwgGep7LlrvgcjF7/gfE7knRZoAEMScnFQu590=,tag:3WtmDivtPs6TzoTDjPoMlQ==,type:str]
    CONFIG_NFS_SERVER_IP: ENC[AES256_GCM,data:s6ZsF9X/dVSQmKs=,iv:B1HtjeQRKWRytCDs8Gt5BoWJOwePvIlNcJPRfvdac3o=,tag:y/7afmnjnLIZ3phBt8E0Vw==,type:str]
    CONFIG_NFS_SERVER_PATH: ENC[AES256_GCM,data:SuRDIrxJxf1n,iv:fOJ/d2yh9k/NMdKX7csN5L87cDvol8K3Ly/ImxDSBEs=,tag:bsKWrNMvYXVkeMgI+oNC8Q==,type:str]
    CONFIG_NFS_BACKUP: ENC[AES256_GCM,data:+h+YhHIcDzUQ3DW7S/GZ750SnNYq3KK/2PyQ,iv:IVBJecYIDw0vl+jl+HHPt8lQS+OmdiX3wpcDp+pWLaA=,tag:cQBy0fB2mJyuuOtF1Zy20Q==,type:str]
    CONFIG_ADMIN_EMAIL: ENC[AES256_GCM,data:x9ZNDo5HWkF5nSIN1i0=,iv:FeCW90RUFoya0t0azabUT1IjLZekEMzwhKpsmIPevLo=,tag:0R79x+q1tPTgj4xXYsyhtg==,type:str]
    POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:Brox4tpOmMdXRZs=,iv:OVYeKaO4ome0KqT0+iXmN3iMT1icDnsWPySCB1QN7bI=,tag:INZiCNAXHG5Mmvld0dQ3XQ==,type:str]
    EMQX_IPV4_ADDR: ENC[AES256_GCM,data:bALBNE4Y+G4qmWax,iv:lRPkExShjKvGNpZRqFmi9L6+j+/wvuhGhp+BFn2uCRw=,tag:/eljq9ovilzJOynG5GZMBQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:9/GGkYMILZaCOmzMd73oClwakcY=,iv:vlTOUUN4FKLpg3TLedBI3LkF5Q1jyngB49f0gf/p6KY=,tag:sNxNQfo2FuXesVWcdOFzBA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TK1kVveTa0gST0ifKY56Zqu/ArhxsGvrQIq6jPebMKxsP4hF,iv:eRqLxWy9n3wLFdQEXGj62NfJHMJsovRggnjq85+QULo=,tag:weFKj/SIQ8xgKfZPTzumQw==,type:str]
    TUNNEL_JSON: ENC[AES256_GCM,data:X7Is6Rb6vvFslOr8dgU3Yb8n/XxHtdxyiuoLAV1cZ0ko66cqKrqg01MleFZ68Xdry0rITZikSzV8n4zLyVWwQqlJZX7KGcaq4XvLRIaSYpFrN6bZ9Ltpbdxy9+brp6zxiIIVzCbCauhnxRAjTsXbBOd1vi7cUKxSZMFLglUqHkhPWBgNDVUGDDcLllhzSetgM1jwLDijVEyrauUIOMB+9+Pv+kPyJ6FEsKLMlBS8rMo=,iv:tyenvZESkFMqqg2msfwo06pLaTOFru9dlj2F57kFdlE=,tag:d13FxBHVillft8pP3OKNsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T07:05:18Z"
    mac: ENC[AES256_GCM,data:A3XrOZzDttr8Ln1iHlceYLPaARReAz2qq6u9EvzmE9Df5AXJoa+bdJnjgnvyHh57BWFdI3BW5UtFxQrbZJq4aTnw7hz7y5/tB4wu4DEiOEa3NHcPfYVkUAF4lGQGAQr9blCmFkSckGG4EKxOoSXlOfmDPXnBzv8XvVVHK/6R1fU=,iv:gkwkDNvb3v17JKHuvTBiurNC+/wtSr2sheAPD0JSEAM=,tag:oPVhDe0+y/mMia6+6gjf6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
