apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:03OimbjpEwfKOcM=,iv:BYYyt676zZ8LGjHzijlojfKRTgpbA7uxGnHD5MTny0A=,tag:fnrp9uey9YvQAV4vmmL5Tg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVjpgCRnqcUITmaGlKY=,iv:s5J/uZwgGep7LlrvgcjF7/gfE7knRZoAEMScnFQu590=,tag:3WtmDivtPs6TzoTDjPoMlQ==,type:str]
    CONFIG_NFS_SERVER_IP: ENC[AES256_GCM,data:etRq53ejhJbN,iv:Twu8AbJJ0SCzV8rTNrxxy2jx1qyKPDPG/mzxQnSmpmA=,tag:usN46p4unthnq4NKRk74xg==,type:str]
    CONFIG_NFS_SERVER_PATH: ENC[AES256_GCM,data:l16xlCosRWhW,iv:qNE1MlQCK/0n87c8xF94v9Oh2fXw2RdJ0E3Y1tfb4Ec=,tag:qkwD2qP9Zxik6L5/kIu9pA==,type:str]
    CONFIG_NFS_BACKUP: ENC[AES256_GCM,data:mzvC4U3gCik5Y6VWpjonqtBigsykW0VzDQ==,iv:PBFLGAWdOh0/kN+f/HWVMfeHS2gNte/07zRRYSZL934=,tag:HrRnqPiNoKiFvRfUCDVMmA==,type:str]
    CONFIG_ADMIN_EMAIL: ENC[AES256_GCM,data:x9ZNDo5HWkF5nSIN1i0=,iv:FeCW90RUFoya0t0azabUT1IjLZekEMzwhKpsmIPevLo=,tag:0R79x+q1tPTgj4xXYsyhtg==,type:str]
    POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:Brox4tpOmMdXRZs=,iv:OVYeKaO4ome0KqT0+iXmN3iMT1icDnsWPySCB1QN7bI=,tag:INZiCNAXHG5Mmvld0dQ3XQ==,type:str]
    EMQX_IPV4_ADDR: ENC[AES256_GCM,data:lvUuXUb45CNanA==,iv:tGg8U2E7ibWO+QwTCxHudqtPSV1G1sAi9GUxDe9OnVo=,tag:rJRCR83aziGoGssXB+GroA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:khYQWEWDM4M0ea4fG8dWkQ==,iv:34sEmB+v3S9wRJbVbNc4KaaCwB1+oICnA35wMX31R9c=,tag:iwbvHEJcdLvwKu95JmYOSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T02:59:53Z"
    mac: ENC[AES256_GCM,data:6MAWO7Ri4fVeMDyqOtfcZnA++wnsMjXZf1rh3cIjqSbXzE4hF3YdqHn4wgMYm3j+BHC/DAITDht4Nsk1q7A0CB0DppsE5HVVzupVumDdNRadJbuGXwkklbzh7Pk8QM/aMLVyasB61/05mjWrINptuxbeR/Ir7XiZo3AUCdXXm4M=,iv:eHM4R0uSGP/+mdxIPKy2hlpZHEBbFZCWywH3RTQc7U8=,tag:dyrj7UEt82wA1RWZ/SV74w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
