apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:z/L2SX5MHlbAk+o=,iv:ec6QPJbIB2mzwqYStmILCUZ4UeTwmL7nKCOM8Ux2IBc=,tag:KWdSbo3RojW7nbGmDgCe4Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVjpgCRnqcUITmaGlKY=,iv:s5J/uZwgGep7LlrvgcjF7/gfE7knRZoAEMScnFQu590=,tag:3WtmDivtPs6TzoTDjPoMlQ==,type:str]
    CONFIG_NFS_SERVER_IP: ENC[AES256_GCM,data:EinrEeSWa6g6,iv:VxH8YPmMiCkH/Y4SOjgl18IVW+wZjC6DvsutzZul5y0=,tag:GcTWeCzTqnqcCMTIKfBsLg==,type:str]
    CONFIG_NFS_SERVER_PATH: ENC[AES256_GCM,data:SuRDIrxJxf1n,iv:fOJ/d2yh9k/NMdKX7csN5L87cDvol8K3Ly/ImxDSBEs=,tag:bsKWrNMvYXVkeMgI+oNC8Q==,type:str]
    CONFIG_NFS_BACKUP: ENC[AES256_GCM,data:DmwTgNPZ7GnN+DksXr+iPRw1Aqd3PgisrQ==,iv:+3ZJuYsYLx44D18rQsq91L63/LutJ9yZJC63Ahop/Wg=,tag:5LORl4dXaVLAKkxziFiyyA==,type:str]
    CONFIG_ADMIN_EMAIL: ENC[AES256_GCM,data:x9ZNDo5HWkF5nSIN1i0=,iv:FeCW90RUFoya0t0azabUT1IjLZekEMzwhKpsmIPevLo=,tag:0R79x+q1tPTgj4xXYsyhtg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:hy8FWEv4P+84trQ=,iv:BR8HZHzzj7dDsxVcc5+Ll44T6OFwhwJRqlHze1lZCPo=,tag:wrOC36ON4hCC18Bh2cPq0Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:dXLmmrVqmbKHieuG0pOSHg==,iv:flb9xkE0BwFyQJ1ePFpqDOny/sYr5AFVz2YCdqJm8AA=,tag:aZfMwv1xgA0ZQUaV9d47TA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ipcLJeSeB2tgITVo+hT63P0uvPLuneFCXF9+ZGRqKMtTZY2u,iv:ka3DLXInEsx3CmClzxGjEPuoQPoM7Z7Ige8EgpLXJe0=,tag:4DgWud/F9FJBMat33rBYKg==,type:str]
    GITSYNC_USERNAME: ENC[AES256_GCM,data:93zNtos=,iv:LO86gYCxCHjsxGKW28e/IrK4KWKy/sDyrBohYAxQefs=,tag:zAjNSlmKAzaagQxzwf7u5Q==,type:str]
    GITSYNC_PASSWORD: ENC[AES256_GCM,data:bN+rxv8c3iB7gjOfxwbvf7emK2CG2zg5APm7eSTJfnn64C9CbgEiYQ==,iv:yQ3DUxtK7Gjby93DxyINxhm9ueXA522oMFOhaxUz1z4=,tag:AwAgKYA+PMyqi0Fz1X0gtA==,type:str]
    INFLUXDB_USER: ENC[AES256_GCM,data:CqNs2ZTvgbg=,iv:W7x1dJhhrLFVyiNbIgtLsJ4Q6GMUavz7ZTOtDwtK0c8=,tag:aaDcMJFJOmc6wq0qusJuWg==,type:str]
    INFLUXDB_PASS: ENC[AES256_GCM,data:Hyj0cX1WHtg1ynQ=,iv:6QQm+WREet8PnCc9WwOx7cKC1IceZcXegzNIbCvlkkg=,tag:oS4mvfXmHkS1wJx9fIGoQw==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:zHKgKjasqWIXFImUlJiVfPL+KzU=,iv:eKlVtQEGt4/mQHEFOw+4NaDJzDu9uwmIPxOyY9bImJM=,tag:8xnTIL90kjBPBhap5y8T/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T03:13:46Z"
    mac: ENC[AES256_GCM,data:d0xSdLGHU82534GFmFN/gxDBSlgerYRTdQpqP/22T5TgK0hpk8EjVuppC4KhHZPrunyOv6gt0QGwtUDkyT8R7CIZMupVp+iKibyppwLCnLsJpBHt9TL/SG1L6TgUM6cMPGoaOcEqILbGJkcedCsGJ2gEI+pND3MccL92reHjWo0=,iv:i8zHZOo/ys8LtoRpOeyUnGUSFuB/0zzqGPIp/lwqYmo=,tag:JOfpctVK0+mCuL7QjW+f5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
