---
default_packages:
  - bash-completion
  - lvm2
  - nano
packages: []
nfs_exports: []
zfs: []
zfs_pools: []
zfs_pool_options:
  - -o ashift=12
  - -o autotrim=on
  - -O acltype=posixacl
  - -O xattr=sa
  - -O dnodesize=auto
  - -O compression=lz4
  - -O normalization=formD
  - -O relatime=on
  - -O canmount=off

emqx_dashboard_username: "admin"
emqx_dashboard_password: "public"
emqx_users: []
emqx_static_seeds: []
