apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5RQiqVgsjFdZjnI=,iv:OxQwX0Do6LhFNs313tDxMquimsV9/o4im/N75lZl6VA=,tag:QWuMxf3oyRwkLrZCQPFYTg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OVjpgCRnqcUITmaGlKY=,iv:s5J/uZwgGep7LlrvgcjF7/gfE7knRZoAEMScnFQu590=,tag:3WtmDivtPs6TzoTDjPoMlQ==,type:str]
    CONFIG_NFS_SERVER_IP: ENC[AES256_GCM,data:EinrEeSWa6g6,iv:VxH8YPmMiCkH/Y4SOjgl18IVW+wZjC6DvsutzZul5y0=,tag:GcTWeCzTqnqcCMTIKfBsLg==,type:str]
    CONFIG_NFS_SERVER_PATH: ENC[AES256_GCM,data:SuRDIrxJxf1n,iv:fOJ/d2yh9k/NMdKX7csN5L87cDvol8K3Ly/ImxDSBEs=,tag:bsKWrNMvYXVkeMgI+oNC8Q==,type:str]
    CONFIG_NFS_BACKUP: ENC[AES256_GCM,data:DmwTgNPZ7GnN+DksXr+iPRw1Aqd3PgisrQ==,iv:+3ZJuYsYLx44D18rQsq91L63/LutJ9yZJC63Ahop/Wg=,tag:5LORl4dXaVLAKkxziFiyyA==,type:str]
    CONFIG_ADMIN_EMAIL: ENC[AES256_GCM,data:x9ZNDo5HWkF5nSIN1i0=,iv:FeCW90RUFoya0t0azabUT1IjLZekEMzwhKpsmIPevLo=,tag:0R79x+q1tPTgj4xXYsyhtg==,type:str]
    POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:Brox4tpOmMdXRZs=,iv:OVYeKaO4ome0KqT0+iXmN3iMT1icDnsWPySCB1QN7bI=,tag:INZiCNAXHG5Mmvld0dQ3XQ==,type:str]
    EMQX_IPV4_ADDR: ENC[AES256_GCM,data:+2WRaFvVRnWoYA==,iv:J2AdlK3Wpm/pyiDwxuLXC6pzMWPIaDU0q0H1zj5rmhY=,tag:QWbqYeNP4zs7yquptM5Zuw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:dXLmmrVqmbKHieuG0pOSHg==,iv:flb9xkE0BwFyQJ1ePFpqDOny/sYr5AFVz2YCdqJm8AA=,tag:aZfMwv1xgA0ZQUaV9d47TA==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ipcLJeSeB2tgITVo+hT63P0uvPLuneFCXF9+ZGRqKMtTZY2u,iv:ka3DLXInEsx3CmClzxGjEPuoQPoM7Z7Ige8EgpLXJe0=,tag:4DgWud/F9FJBMat33rBYKg==,type:str]
    TUNNEL_JSON: ENC[AES256_GCM,data:mrNkUuIig5TAy1sXsB1c2yfIox5dCPKBkxjbtpGsRqmPYPimkTJJdUw+wAW/vvGRaOUqmuLhPIxbDg1cVDibcNZ82cUt/PgelSMN1VzHNblIGYeaVjziVR8F/2owbvWabzVVA/XOoG4S1ziNXWoUfFeT1oe1X2iMGa1H4IX1uNWSs2Xm+kNI8JM/jNSxpUppkVj+9mMdU8siyGoy9PIxVfOwf7FTw0iwAgMkB/CqZxE=,iv:Kot9n3WtmMWd9U77iOTVJiJfVJcDWOq/jVnIi7sCQZo=,tag:nzJX8J1gzrL6Ntx3xjRmQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRU00UWE5YnFERFpMakw5
            OGhObGJVZ29BYWNmT0E0Q3Z4YXp4VktxdVRJCi9iU2pMcHBmTmJJYlgyaXNRQXhr
            QnNkeWRnLzdpM2JGMGhDSkN2eFZ1anMKLS0tIFpyczIyUG9NK0Q2SWppWmNtRmNn
            VlJDN3BrcjZ3NGVkU1poUFc0SDIyRTgK/NeIEcWXFf1pVuA8hUIjFipUuC6IVZEo
            YgC25B5qSl4WJWEFq/x5KiaQ8q31mbCTma6AmscrsvYnNkociryZnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-29T20:20:30Z"
    mac: ENC[AES256_GCM,data:bDJhw1R7j6lJnk2xFhx1tW0kmcOeC4/m9PTxqL3EgdgRURfTa56ksmhhrUmXt+wVRIoBhGzrt7AlCsvOBVyt4Q/vgs341rZm0fhepXvwULpT849wBk6wgR81zccy+1tz8xXNN3bcZX1crDwYsp4wnzvNDfLIso8EGQVPkloVXlM=,iv:XFe2q7JM2dH12CiQTK4/Rs0uqXeYgYVKiDC5DxwvAOQ=,tag:UMEqGLsjSuX+6GAqPtNQdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
