---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
resources:
  - ./cluster-settings.yaml
  - ./cluster-secrets.sops.yaml
  - ./cloudflared.sops.yaml
