apiVersion: v1
kind: Secret
metadata:
    name: thanos
    namespace: monitoring
type: Opaque
stringData:
    S3_ACCESS_KEY: ENC[AES256_GCM,data:1qcM6zrETOEACPZvE2mujg==,iv:wPRwTt7u8GdJS2qfGFNXP1AJ3G2IoNs25tPA1mE5LSo=,tag:Yx3GdGJMciHXGbCWzaBxtA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:0uUcS0012/djs0y5C7tAciE8w4ICPprc14i77CoRObU=,iv:Qy8LVDU6AaEH1brK8qJCcyGn4pIAfxiwTeXeABhaFw4=,tag:bTwKu5po9fvqO0srngHbrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T02:15:26Z"
    mac: ENC[AES256_GCM,data:mqVA88QvirnfRaXo/XrlrNb9k5KufWPWm7qBB9ibdW7o1Pe9fEnJB4T2NX2AZrc36oUmIXUCd2XCJ81IRsNxPOWFy7hWvXNCW1AiBUFtQv/kb/SmnjMIJZnpUWukfjJHMhJ562QnGv1WSCNLbBcpEjGuXXhw3sUetondO12CNq0=,iv:uK8fC6+/T/vp66lpeBHdtLyUXDWgC1PA/n85rmvGhcc=,tag:PehESR4J9/VlqX+MdY0KKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
