---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
namespace: kube-system
resources:
  - ./rbac.yaml
  - ./daemonset.yaml
labels:
  - pairs:
      kustomize.toolkit.fluxcd.io/prune: disabled
