---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: pgadmin4
      version: 1.14.6
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: dpage/pgadmin4
      tag: 7.0
    nameOverride: pgadmin
    strategy:
      type: Recreate
    env:
      email: "${CONFIG_ADMIN_EMAIL}"
    existingSecret: pgadmin-secrets
    secretKeys:
      pgadminPasswordKey: password
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/appName: "Postgres Admin"
        hajimari.io/enable: "true"
        hajimari.io/icon: simple-icons:postgresql
      hosts:
        - host: &host "pgadmin.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      enabled: false
    persistentVolume:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 1Gi
    serverDefinitions:
      enabled: true
      servers:
        postgres:
          Name: k8s
          Group: Servers
          Port: 5432
          Username: postgres
          Password: "${POSTGRES_ADMIN_PASS}"
          Host: postgresql.database.svc.cluster.local
          SSLMode: prefer
          MaintenanceDB: postgres
    resources:
      requests:
        cpu: 15m
        memory: 128M
      limits:
        # cpu: 15m
        memory: 512M
