apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2kAqq8OJgznv,iv:h1XTCq9dGycEcGSQp3rRjFtH0D7Ah0CGT3eVUihmn9Q=,tag:bYMUlimQ4baPceCsWdAfcg==,type:comment]
    #ENC[AES256_GCM,data:HylrdVNxslTuEOeD21jbjpplgS1PEr0ZiKWim12q05V7myy4gVwAU9E4gF63f6QSwnKDYsH1d4prDQkFmNejXU/clPv6pn670oqGvrCaLbiuvhTui72lX8OniiVWu44NKGV27ec=,iv:9HcRsrt0qkVxIS8490A4sIsAlLnxSAHfVfZwecQ4cGU=,tag:nZoFuoPlhG2FsOvcAuCOWQ==,type:comment]
    #ENC[AES256_GCM,data:TY1a2Z8kGK35ZbEkuHb2//QwO9BhgdjzUNyd04I1XjQGFFXF0RpiCQNn7vKuaVXjRQRWt/Wr6HnLbUjofzdRf5zyrsscMr8RJuET0g1M/6fcAelCuSU9rp6i7+akHVf51F5j,iv:P98+TUhO1EPxL5fJAYOxkhoftaJij99MZQH2GSxjdvQ=,tag:K+TJTOYwCpyIcVpPB1mQjQ==,type:comment]
    #ENC[AES256_GCM,data:znc+25gn1pW1pG6f7ADixD1wWWs9C43wuwfIRFzX3aIbi2QArT8SnViifp7NEokGrrihDdU80hXLhOiFFizxnJuOhSH7/st1OzOdxFlFWKqmL6H7bbj8lDREQjMpoPCXFuTScYpgaCUuwu/D3LKCc1E=,iv:AAJGCtzhOVWk6KkMvCDZQvrW3T2HvQkClJLpe23Qo+I=,tag:JoC3Vt6wn29qK6m/tUAsrw==,type:comment]
    #ENC[AES256_GCM,data:W3aoxJ+B185E+RmD+0G0HBgKPYfeIfI02LcjpzsauiNfvcTM/i1xEEMt1IXtd/xVtQ==,iv:GKjZQP4aBNbv7GyjLmho2uvsfyEc9PgHE4vwcjEBqQs=,tag:sSL7ChqTi6eCeyAhgaDmcg==,type:comment]
    #ENC[AES256_GCM,data:l6DFktK74AvLXR8pawLz0RUYni9DRHngTFwwVh6cH1s8m8/tVV9ULslS+qEy0S9HIz41fQuKh0Pr,iv:9EcDOB+rqTTATqC0zAT9ftsHBKvwpME8rdBXWyUYxzI=,tag:RWH7wmOTr7yFHWzwwjEgYw==,type:comment]
    #ENC[AES256_GCM,data:0W/1pBZ1JhUtO+rjcXu05D5t2AAUrAgLuQtcMkVpNXPsmMWPQ77/pARpBJ17OaOcXsydxf5EBnUG6erRTM3wsBN0SKESTWUm4Q==,iv:Fdz/cQtWByeJ9YBGRxsmjJYMOShfwNLSpYrdMI9u8ao=,tag:QQ0BEld1CeJal9H/ERBmsQ==,type:comment]
    AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:9JQwVYUCWas=,iv:welASI/rHvwWkxCJNr/7HanzyeVohreZaU6NdHS7uGY=,tag:AH/KqJW7QLj/G9TcZXvVow==,type:str]
    AUTHELIA_STORAGE_POSTGRES_HOST: ENC[AES256_GCM,data:J8WAP7XWbOKoQjNQZCHiu7msAz0lYIiTGFGP0Je4JxXvH3FPEg==,iv:UrnlKpPz7OjTRtQqugCZdHzYCI4DGppbqdeH4BsDA6U=,tag:H/2JNJopiA+o/PKJ1HZHZA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:sVx8SubQPoJdBjc=,iv:+VOckCNN8ptjEQm1x2nWBSdYzELMp276fcX86ZhJ9SU=,tag:3yFuI9nzRxsiyYpB4BTjjA==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:ouzn+MzCHPk=,iv:uZ9jHqi7ShuTyw0U+v9kdULyyZhzVk0jMv7Qhd/a8y8=,tag:nLE31HkVWrZ4h4rJznWmMw==,type:str]
    #ENC[AES256_GCM,data:vNHhFjxYSng4Qg==,iv:Wta4RA0dxZC9mElSoeIsPRdVN/1XQ0Q+TccierxVPiM=,tag:Jv8VtbAgF1RDz/EjMmrqnQ==,type:comment]
    #ENC[AES256_GCM,data:CcKBQkdDYKfSAXQFIexxo6BUDr0EISs6WMrqtlGenPvLqqHXSGmo09LmPkec80uEczFltGPWReXD3xbXX6sbmBk=,iv:iFHpxMQbdyL8D302fQGBBz3w04gzQyHJJqSmEErr6o0=,tag:6KX/4luWnOz586NuG3GW0w==,type:comment]
    #ENC[AES256_GCM,data:x0lew19saH7jA1wb1kWu9IhHaKeWbHrg0/qfgEPdHiozMizNojs9XqeYUUnqh/YL/W8dShEjZKDT6r/8OGov,iv:O6PgATu4W0XxlE0fCcLcSPkFMPZm6gl2p8l+lcwab1Y=,tag:2wW+c5mhYl7VLrk3NnrLEw==,type:comment]
    #ENC[AES256_GCM,data:CBmkb9sSZeztYVAl5vr8Ty3hei8Ls7aOrufkATI5NDjNlerDqIDjxoIbJ36s1akKpm5beBe8pFIXTjo09lUXb5G3eg==,iv:55v925qUl2bVQadKTQa4SXeBI4AhPqb0Jyv2cQka+uU=,tag:/8YfYBL/xBrY6MlLr56x0A==,type:comment]
    #ENC[AES256_GCM,data:WNrkImOw13n11Y62+rvb0YUem/jYZZ52Oxz2UXzSa2xyGWRSV8XY6AjHHMi34Eat5s1nBr8KhWmxdnoHn3ut+tMYhrqYJArJJQ==,iv:m24jNdxDqD7qn/mV8x+90ustIf01rJJPZBaTbk502RE=,tag:2wk3G2iex8s5Tmzh2CJY8Q==,type:comment]
    #ENC[AES256_GCM,data:WGKsfFyzu6uVgWJ/mVBtjaDomSYIOYzlc9n2Ix/elYXno3xM2WON5sGxQjIdhz0froveWxb/qEUSIpEEUA==,iv:OJKIQZSM20JnifJZLWLpzYCDHaB6JMTRq5zFwdmBGSw=,tag:g86TG9DWHdLV0XOf5PXXhg==,type:comment]
    #ENC[AES256_GCM,data:9M4trajulJO5DBUqATU=,iv:kowV1FZgvi0Rdih3CiVsARufTdME76F48lBQbwf8kos=,tag:npMEWbtXVjqoQLyw7mJA1w==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:3M3kvaLfRNw=,iv:DlbdJbV4hfHR+yA/9EkWRHDP1vrr9mpYKnh+e0mlFpI=,tag:smVDOIPpZ+z2cBGTSUwJpA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:za2hQriXeElF3SkSNqT+DSz+Vcm6izuA81Z8FZkWxDEeO8k9+A==,iv:wxLMTtbpa6UHEx5dkfsa8rthhO6FkrTq+1aZBFfyXiU=,tag:iW8nlLn2vTV470kA6M5xfA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:0DhljyvT/MXhHwE=,iv:SWx4Uu0i26S8sEL3KmK00Xh9hlZWUs1Vi1jrCMSd044=,tag:UbPwe4VL6uI06c0TQuDhEA==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Bi7A/58ypvCQWbI=,iv:wlWHfduozRDuNwx6nc7jHJLrrfswpPGiF9JNbsBmQ9c=,tag:FvIqpkrQ8Ik5227VmtJRhw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:UMeeeIXoWoI=,iv:oeFnm9TOIYWf8hE41jb0wwZqCtWMywTYa9TbfmjYOrU=,tag:if33j0V1keb07vzibvgG3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-05T20:45:31Z"
    mac: ENC[AES256_GCM,data:0i994ugDrnXl4Wr+bXPEf4ZzhA41HbOrC1ErZjUcQsF06I3Fhlt7qrmU4rDn4NszxTHXNpdulZiegyzbQuXn2/kfZoYQvcpCOEH6vaPwZrHwpuaf8AXLpQQeUoKXk5DCmmePvkDtWbV+CiUFuYAwC6JdaWKHj4osY6UjhCCMtrw=,iv:pxbhzDK93+7AgFYVf9e/kazfEyeg6suCicXYY/7s8oU=,tag:Cos1LvAQUK4KNmVvrmaGng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
