---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant-config
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: registry.k8s.io/git-sync/git-sync
      tag: v3.6.5

    env:
      GIT_SYNC_REPO: https://github.com/kilip/hass-config
      GIT_SYNC_BRANCH: main
      GIT_SYNC_ROOT: /hass-config
      GIT_SYNC_LINK: current
      GIT_SYNC_ONE_TIME: "false"
      GIT_SYNC_ADD_USER: "true"
      GIT_SYNC_USERNAME: "${GITSYNC_USERNAME}"
      GIT_SYNC_PASSWORD: "${GITSYNC_PASSWORD}"
      UID: 568
      GID: 568

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    envFrom:
      - secretRef:
          name: home-assistant-secret

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    args:
      - "-depth=1"
      - "-v=3"

    persistence:
      - name: hass-config-v1
        mountPath: /hass-config
        existingclaim: hass-config-v1
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    service:
      main:
        ports:
          http:
            port: 8080
