---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.7
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: home-assistant-secret
        env:
          POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"
      02-init-config:
        image: registry.k8s.io/git-sync/git-sync:v3.6.5
        env:
          GIT_SYNC_REPO: https://github.com/kilip/hass-config
          GIT_SYNC_BRANCH: main
          GIT_SYNC_ROOT: /tmp/hass-config/config
          GIT_SYNC_DEST: latest
          GIT_SYNC_ONE_TIME: "true"
          GIT_SYNC_ADD_USER: "true"
          GIT_SYNC_USERNAME: "${GITSYNC_USERNAME}"
          GIT_SYNC_PASSWORD: "${GITSYNC_PASSWORD}"
          UID: 568
          GID: 568
        args:
          - "-depth=1"
          - "-v=3"
        securityContext:
          runAsUser: 568
          runAsGroup: 568
        volumeMounts:
          - name: &config-pvc hass-config-v2
            mountPath: /tmp/hass-config

    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.4.6
    env:
      TZ: "${TIMEZONE}"
      POSTGRES_HOST: postgresql.database.svc.cluster.local
      POSTGRES_DB: home_assistant
      POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"
    envFrom:
      - secretRef:
          name: home-assistant-secret
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    volumeClaimTemplates:
      - name: *config-pvc
        mountPath: /config
        subPath: config/latest
        accessMode: ReadWriteMany
        size: 1Gi
        storageClass: longhorn

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 512Mi
