---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hass-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
