apiVersion: v1
kind: Secret
metadata:
    name: openhab-secrets
    namespace: home
type: Opaque
stringData:
    cloud_uuid: ENC[AES256_GCM,data:4sXIQ+HPZDXBtfFyZRQaCWNkkgYn37Edbg4LOZFwf+AJ6AWy,iv:mRHFL43/RJCOb+TtSaJ1ZTIlE5rKf9IyDoyKuhdurOA=,tag:elLOSBIe46ek76hNFeChig==,type:str]
    cloud_secret: ENC[AES256_GCM,data:LcCw1JakwoXB1a3mCua9BP/2FJg=,iv:jXWrYjTyoPb39HHZ90Rf0VmlVOAiP207d8H/CgISeUU=,tag:y5zMz44b9t2+zOP84VlQlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-20T06:46:43Z"
    mac: ENC[AES256_GCM,data:mFdnxYWyuFvS0RrA5SMYb+DaSSban8pjvZrIGauCdph+NYjEwGL5XPoPCuNCSa6NvFO9beXKaQ0L12Pks++aSZ4g7f5BoUXAfqInL3meb4hHAxtRR9DVL3xeUEnfZsIh1xocrXND4PCuJBl9+S35rpY2m9dsD7F6HTf3cWBHxak=,iv:Ra1zpRo2XUlISzBqS+9TFrPvezwU4+r3asT/IUtqyis=,tag:ML5FIQM4hb15UJUztQHiTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
