apiVersion: v1
kind: Secret
metadata:
    name: emqx-config
    namespace: home
type: Opaque
stringData:
    admin_password: ENC[AES256_GCM,data:HMCgPg6pojSkWtU=,iv:3A2kQ9KTyl4sI2InQIqPrAJ1+YCKu7a4pkrKZuqXsWg=,tag:ttdI1W2qrRVilF/7E8XWcQ==,type:str]
    user_1_username: ENC[AES256_GCM,data:bSnAGw==,iv:Oryn4F4YBNSxe3y0Whl/d0gurjqbgVu2FoDBCUTRKFo=,tag:eOhmpuC7VR0rZmcsoBTfGQ==,type:str]
    user_1_password: ENC[AES256_GCM,data:8e5nsPPH9AZPjoQc7VQ=,iv:dt6IGqCE9v/iPY5rnWIPzE7WGbU2NuDLzAxeuL5N52M=,tag:kdn2kfiAbavj8p6/ZFl2iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age180j8sem3rdazaszzpsyv4rshkxt677qz2nluhc25ydvpa6c9c9eq94qkze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZWFEemdFNjlRNXJJMUJi
            RnJCcXl2amhsbDBKNU92eGlhK3J2b0cva2pjClpndFV2TmVqeWlUbldyMDdmaVhJ
            K3pscjFuZk9lazM0L0wzVUZKZjAxcE0KLS0tICtMUFpCNlp6ZEI3TjVVZTd3eW1T
            bEQ0OHhiZUhoNjd0U1ozanZ1UVlGMVEKNtqBzRp+TwDTX4AiiGnQnTMFW1rTHC4J
            Dmw+/9PtYLuVq2uIaJIUgK8T+wORPBSKug+xzAMrfuhTKqHB9SbCWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T17:06:31Z"
    mac: ENC[AES256_GCM,data:s4t/bjla1wEEDAvpnDBO66LaaYd7Z+QI2aNreiOfiGYOu+vu+n7MwZnAkv+9nQ2cdbtk/x/pEupp+g8d3OeQQTVZal5OSR5Zop66vcEWIXd8qeepe6G1bsIJtAdlJaq7/iE8QqB8Lz3yyQ89gxrKzy93tJuo8V7/xuD1Kzr/FbM=,iv:BAYULXKTEbkTyYu5KXPrapFcZtspFaJsxkOjXt8pfdk=,tag:XUZmBfoi5QrR4WUKTkvdew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
