---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-vip/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
